import streamlit as st
from datetime import datetime
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain.chains import LLMChain
from langchain.memory import ConversationBufferMemory
from langchain_core.prompts import PromptTemplate
from langchain_openai import OpenAI
import streamlit as st
import os
from fpdf import FPDF
import json
import streamlit_lottie as st_lottie
from streamlit_ace import st_ace
import pyaudio
import wave
import readtext
import sp

os.environ["OPENAI_API_KEY"]=os.getenv("OPENAI_API_KEY")
os.environ["LANGCHAIN_TRACING_V2"]="true"
os.environ["LANGCHAIN_API_KEY"]=os.getenv("LANGCHAIN_API_KEY")

# behav_arr=["","Tensorflow"]
# levels_arr=["basic","normal","hard"]
candidate_response=""
response=[]
memory = ConversationBufferMemory(memory_key="chat_history")
CNT=2
llm = OpenAI()

def load_lottie(filepath: str):
    with open(filepath, "r") as f:
        return json.load(f)

human_talking = load_lottie(r"D:\abhijith\ML\pravaah\assets\coat.json")


class AudioRecorder:
    def __init__(self):
        print("CALLEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD")
        self.filename = "recorded_audio.wav"
        self.channels = 1
        self.sample_rate = 44100
        self.chunk = 1024
        self.audio_format = pyaudio.paInt16
        self.p = pyaudio.PyAudio()
        self.stream = None
        self.input_device_index = None

        self.list_input_devices()

    def list_input_devices(self):
        info = self.p.get_host_api_info_by_index(0)
        num_devices = info.get('deviceCount')
        for i in range(num_devices):
            device_info = self.p.get_device_info_by_host_api_device_index(0, i)
            if device_info.get('maxInputChannels') > 0:
                self.input_device_index = i  # Choose the first available input device

    def start_recording(self):
        self.stream = self.p.open(format=self.audio_format,
                                  channels=self.channels,
                                  rate=self.sample_rate,
                                  input=True,
                                  input_device_index=self.input_device_index,
                                  frames_per_buffer=self.chunk)

        st.session_state['recording'] = True
        self.frames = []
        while st.session_state['recording']:
            data = self.stream.read(self.chunk)
            self.frames.append(data)
        
    def stop_recording(self):
        st.session_state['recording'] = False
        self.stream.stop_stream()
        self.stream.close()

        # Save the recorded audio as a PCM WAV file
        wf = wave.open(self.filename, 'wb')
        wf.setnchannels(self.channels)
        wf.setsampwidth(self.p.get_sample_size(self.audio_format))
        wf.setframerate(self.sample_rate)
        wf.writeframes(b''.join(self.frames))
        wf.close()

@st.cache_resource
def instantiate_class():
    return AudioRecorder()


def save_transcript(chat_history):
    class PDF(FPDF):
        def header(self):
            self.set_font('Arial', 'B', 12)
            self.cell(0, 10, 'Chat Transcript', 0, 1, 'C')

        def footer(self):
            self.set_y(-15)
            self.set_font('Arial', 'I', 8)
            self.cell(0, 10, 'Page ' + str(self.page_no()), 0, 0, 'C')

    pdf = PDF()
    pdf.add_page()
    pdf.set_title('Chat Transcript')
    pdf.set_author('Generated by Python Script')
    pdf.set_font('Arial', '', 12)
    for line in chat_history.split('\n'):
        pdf.cell(0, 10, line, 0, 1)
    pdf.output('chat_transcript.pdf')
    st.success("PDF created successfully!")

def hr_questions():
    
    template = """You are an expert recruiter conducting a HR interview for a software engineering position. MUST RETURN question:""
    Previous conversation:
    {chat_history}
    AI:"You must questions based on previous reply of user NOT technical ONLY behavourial questions. MUST RETURN question:""
    YOU SHOULD NOT REPEAT PREVIOUS QUESTIONS
    """

    prompt = PromptTemplate(
        input_variables=["chat_history", "HR"], template=template
    )
    llm_chain = LLMChain(
    llm=llm,
    prompt=prompt,
    verbose=True,
    memory=memory,
    )

    data=llm_chain({"HR":"behavourial and company culture"})
    response.append(data['text'])
    return data['text']


def load_messages():
    if 'messages' not in st.session_state:
        st.session_state['messages'] = []
        # Add initial AI message when no messages are present
        st.session_state['messages'].append({
            'username': "AI",
            'text': "I am your AI interviewer. Enter 'ready' to start the interview.",
   
            'time': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        })

    return st.session_state['messages']

# Function to save a new message
def save_message(username, text):
    messages = load_messages()

    messages.append({'username': username, 'text': text,'time': datetime.now().strftime('%Y-%m-%d %H:%M:%S')})
    st.session_state['messages'] = messages

def save_transcript(chat_history):
# Chat history data
    data = chat_history

    class PDF(FPDF):
        def header(self):
            self.set_font('Arial', 'B', 12)
            self.cell(0, 10, 'Chat Transcript_HR', 0, 1, 'C')

        def footer(self):
            self.set_y(-15)
            self.set_font('Arial', 'I', 8)
            self.cell(0, 10, 'Page ' + str(self.page_no()), 0, 0, 'C')

    # Create instance of FPDF class
    pdf = PDF()

    # Add a page
    pdf.add_page()

    # Set title and author
    pdf.set_title('Chat Transcript')
    pdf.set_author('Generated by Python Script')

    # Add chat history
    pdf.set_font('Arial', '', 12)
    for line in data['chat_history'].split('\n'):
        pdf.cell(0, 10, line, 0, 1)

    # Save the pdf with name .pdf
    pdf.output('chat_transcript_HR.pdf')

    print("PDF created successfully!")


def main():
    st.set_page_config(page_title="Chat App", page_icon=":speech_balloon:")

    
    st.markdown("""
    <style>
        .main-title {
            font-size: 2.5rem;
            color: #FFA500;
            text-align: center;
            margin-bottom: 20px;
        }
        .sidebar .block-container {
            padding-top: 2rem;
        }
        .chat-message {
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 5px;
            background-color: #333333;
            color: white;
            display: flex;
            align-items: center;
        }
        .chat-message:hover {
            background-color: #2b2b2b;
        }
        .message-time {
            font-size: 0.8rem;
            color: #888;
            margin-left: auto;
        }
        .form-container {
            margin-top: 20px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .form-container .css-1cpxqw2 {
            flex-grow: 1;
            margin-right: 10px;
        }
        .form-container .stButton button {
            width: 100%;
            background-color: #4CAF50;
            color: white;
            border: none;
            padding: 10px;
            border-radius: 5px;
            cursor: pointer;
        }
        .form-container .stButton button:hover {
            background-color: #45a049;
        }
    </style>
    """, unsafe_allow_html=True)

    st.markdown('<h1 class="main-title">AI Bot</h1>', unsafe_allow_html=True)

    st.markdown('<div class="lottie-container">', unsafe_allow_html=True)
    st_lottie.st_lottie(human_talking, key="1", height=200, width=200)

    if 'editor_visible' not in st.session_state:
        st.session_state['editor_visible'] = False

   


    # Sidebar for user information
    with st.sidebar:
        st.header("User Info")
        username = st.text_input("Username", key="username")
        if not username:
            st.warning("Please enter a username to join the chat")
            st.stop()
    st.sidebar.header("Audio Controls")
    if "my_class" not in st.session_state:
        st.session_state.my_class = instantiate_class()
    
    if st.sidebar.button("Start Recording"):
        st.session_state.my_class.start_recording()

    if st.sidebar.button("Stop Recording"):
        st.session_state.my_class.stop_recording()

    st.header("Chat")
    if st.button("Submit", key="transcript_button"):
        # Get current chat messages
        messages = memory.load_memory_variables({})


        # Save transcript as PDF
        pdf_file_path = save_transcript(messages)

        # Provide a link to download the PDF
        # st.markdown(f"[Download Transcript PDF]({pdf_file_path})")

    # Display chat messages
    messages = load_messages()
    for message in messages:
        st.markdown(
            f"""
            <div class="chat-message">
                <div>
                    <strong>{message['username']}</strong>: {message['text']}
                </div>
                <div class="message-time">{message['time']}</div>
            </div>
            """, unsafe_allow_html=True)

    # Input form for new messages
    with st.form(key='message_form', clear_on_submit=True):
        st.markdown('<div class="form-container">', unsafe_allow_html=True)
        message_text = readtext.read_text_file()
        submit_button = st.form_submit_button(label='Send')
        st.markdown('</div>', unsafe_allow_html=True)

    if os.path.exists("recorded_audio.wav"):
        try:
            sp.speech_to_text()
        except Exception as e:
            st.error(f"Error processing audio: {e}")
    else:
        st.warning("No recorded audio found to process.")
   

    if submit_button and message_text:
        global k
        # marks=similarity(candidate_response,response_ans[-1])
        save_message(st.session_state['username'], message_text)
        latest_user_message = message_text

        ai_question=hr_questions()

        # if(k==0):
        #     ai_question = get_ai_response("")
        # elif(k<2):
        #     ai_question = get_ai_response(latest_user_message)
        # else:
        #     ai_question = get_project_response(latest_user_message)

        print("AI Response is ",ai_question)
        save_message("AI", ai_question)
        st.experimental_rerun()



if __name__ == "__main__":
    main()