from fpdf import FPDF

# Chat history data
data = {'chat_history': "Human: hi!\nAI: what's up?"}

class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, 'Chat Transcript', 0, 1, 'C')

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, 'Page ' + str(self.page_no()), 0, 0, 'C')

# Create instance of FPDF class
pdf = PDF()

# Add a page
pdf.add_page()

# Set title and author
pdf.set_title('Chat Transcript')
pdf.set_author('Generated by Python Script')

# Add chat history
pdf.set_font('Arial', '', 12)
for line in data['chat_history'].split('\n'):
    pdf.cell(0, 10, line, 0, 1)

# Save the pdf with name .pdf
pdf.output('chat_transcript.pdf')

print("PDF created successfully!")
